name: Release

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        

    - name: Build without test
      run: mvn -B package  -Dmaven.test.skip=true package --file pom.xml

    - name: Start proxy service(libreoffice)
      run: java -jar libreoffice-api-wrapper-server/target/libreoffice-api-wrapper-server-3.1.8-jar-with-dependencies.jar

    - name: Start docker
      run: docker run -t --name libreoffice -p 8100:8100 hdejager/libreoffice-api

    - name:
      run: mvn test
